### ISSUE TITLE
Store Refresh does not work for refresh all as stated in the documentation

### ISSUE THREAD

**Issue by pmerchnow** [marketvision/ShipStation4Net#16]
store refresh states that if no store id or date is specified then it will update all stores. however store id and date are not nullable therefore you always need to pass in a store id. 

If you pass in a 0 and a new DateTime() you get an internal Server error. Therefor you always need to iterate through each store and call a refresh on each store to get this to work.

**Comment by vlad-kurdesov** [comment]
Sorry for delay, I didn't know about this issue on this package earlier..
this should be fixed in 0.10.70 package (I just pushed to nuget.org)
You were right about integration issue - method to refresh all stores was not available
Pull request #18 added `Stores.RefreshAllStoresAsync` method on client
